# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # NuGet updates will also trigger updates to the corresponding
  # chocolatey packages because of how our build scripts operate.
  - package-ecosystem: "nuget"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: NUnit
      - dependency-name: NUnitLite
      - dependency-name: NUnit.Extension.*
    groups:
      testcentric:
        patterns:
        - "TestCentric.*"
